name: update-flow

on:
  workflow_dispatch:

jobs:
  update-data:
    name: Update Main Data
    runs-on: ubuntu-latest
    steps:
      - name: checkout GrcData
        uses: actions/checkout@master
        with:
          repository: 'HeYaoDaDa/GrcData'
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: run script
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ vars.APP_ID }}
        run: npx tsc && node dist/app.js
      
      - name: checkout self
        uses: actions/checkout@master
        with:
          path: 'self'
          persist-credentials: false
          fetch-depth: 0
      
      - name: prepare comit
        run: rm package*.json;cp -f *.json ./self

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          force: true
          directory: './self'